---
- name: Update apt-get repo and cache
  become: yes
  apt: update_cache=yes force_apt_get=yes

- name: Upgrade all apt packages
  become: yes
  apt: upgrade=dist force_apt_get=yes

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: Install PM2
  become: yes
  npm:
    name: pm2
    global: yes

- name: Intall package git
  become: yes
  package:
    name: git
    state: present
